### ISSUE TITLE
<p>标签问题

### ISSUE THREAD

**Issue by z8227876** [wangeditor-team/wangEditor#1665]
1. 我在富文本里赋值的时候,然后修改样式后保存,有时候最后面会有一个< br >或者是< p >< br >< /p >,请问这个该如何处理?
2. 用< p >标签时,换行的行距太大了,中间像空了一行,如何设置行距?或者说如何将< p >标签转换成< div >,除了replace替换..

**Comment by ultravires** [comment]
样式很好控制，写一个css样式即可  类似这样：
```css
.editor>p {
  padding:0;
  margin:0;
}
```

但是 p 标签不允许嵌套其它块级标签是重点。如 p 标签下不允许有 div 标签
