### ISSUE TITLE
增大了编辑器的7个字号，但是输入时无法指定默认字号，还是要手动修改

### ISSUE THREAD

**Issue by yangfeng1003** [wangeditor-team/wangEditor#3044]
## 问题描述

*如何修改输入时默认的字号*

## wangEditor 版本

*4.6.5*

## 是否查阅了文档 ？

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
 默认的字号较小，因此将7个字号改为更大的数字。
```js
editor.config.fontSizes = {
      'x-small': { name: '28px', value: '1' },
      small: { name: '30px', value: '2' },
      normal: { name: '32px', value: '3' },
      large: { name: '34px', value: '4' },
      'x-large': { name: '36px', value: '5' },
      'xx-large': { name: '38px', value: '6' },
      'xxx-large': { name: '40px', value: '7' },
    };
```
 ```css
 font[size='1'] {
  font-size: 28px;
}
font[size='2'] {
  font-size: 30px;
}
font[size='3'] {
  font-size: 32px;
}
font[size='4'] {
  font-size: 34px;
}
font[size='5'] {
  font-size: 36px;
}
font[size='6'] {
  font-size: 38px;
}
font[size='7'] {
  font-size: 40px;
}

```

- 步骤二
 输入时的字号依然是修改之前很小的字号
- 步骤三
如下图  新的字号确实手动修改生效，但是在没有修改之前输入的依然非常小。希望代码可以默认就是32px，无需手动设置

![image](https://user-images.githubusercontent.com/44138013/111407825-3ea21180-870f-11eb-96bb-37b7c2800b68.png)
