### ISSUE TITLE
p 标签字体样式的 important

### ISSUE THREAD

**Issue by ForzaMichael** [wangeditor-team/wangEditor#3422]
## 问题描述

因为有此important样式导致字体的样式不生效

## wangEditor 版本

4.6.14

## 是否查阅了文档 ？

是
无相关内容

## 最小成本的复现步骤
p 标签样式

```
.w-e-toolbar p, .w-e-text-container p, .w-e-menu-panel p {
    font-size: 1em !important;
}
```

**Comment by rsl140** [comment]
![image](https://user-images.githubusercontent.com/7655291/123888142-67c87400-d985-11eb-9109-67636897af8d.png)
尝试这样配置
``` css
#div1 .w-e-text-container p {
    font-size: 10px !important;
}
```
