### ISSUE TITLE
编辑区域高度 < 300px 这可能会导致 modal hoverbar 定位异常

### ISSUE THREAD

**Issue by master-genius** [wangeditor-team/wangEditor#3796]
## 问题描述

我按照文档说明给标签加上了样式限定：min-height:320px;但是总是在控制台输出警告：

编辑区域高度 < 300px 这可能会导致 modal hoverbar 定位异常

## wangEditor 版本

v5

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是*

## 最小成本的复现步骤

```
<div id="my-editor">
    <div id="editor-toolbar"></div>
    <div id="editor-container" style="min-height:320px;"></div>
</div>
```

**Comment by wangfupeng1988** [comment]
没关系，这只是一个 warning 而已。如果你觉得使用没问题（如 modal 定位没问题），就不用管他。

**Comment by wumiangithub** [comment]
我就是想要默认高度小于300，因为我是simple模式，这警告看的老难受了

**Comment by wangfupeng1988** [comment]
> 我就是想要默认高度小于300，因为我是simple模式，这警告看的老难受了

这里就应该警告你啊，小于 300 会影响 modal 的展示。不过，警告不是 bug ，不影响你使用。

**Comment by rain2307** [comment]
我都设置500了怎么还报，css写了，inline style也写了。

**Comment by hyvp** [comment]
给这个css类添加一个固定高度：.w-e-scroll { height: 500px;或height:auto;  或calc(100% - 1px)}

**Comment by SuperX27** [comment]
设置以下style可以解决问题
```scss
  :deep(.w-e-text-container) {
    .w-e-scroll {
      height: auto;
      min-height: 300px;
    }
  }
```
