### ISSUE TITLE
ul和ol列表的对齐方式无效

### ISSUE THREAD

**Issue by JackieCheung** [wangeditor-team/wangEditor#3821]
## bug 描述

ul和ol列表的对齐方式无效

## 你预期的样子是？

ul和ol列表整体对齐（居左、居中、居右.....）

## 浏览器及版本号

Chrome

## wangEditor 版本

4.7.11

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤
只能设置其中的li对齐方式
![image](https://user-images.githubusercontent.com/31252046/148358949-e7f22f2c-7eb6-4eda-ad1d-5fa19f87c8e3.png)

**Comment by wangfupeng1988** [comment]
已合并代码，等待下一个新版本发布。

**Comment by Gavin-yh** [comment]
> > 已合并代码，等待下一个新版本发布。
> 
> 我刚刚看了一下改动的代码，除了ul列表，ol列表也需要做同样的处理

有序列表是没有过滤的

**Comment by JackieCheung** [comment]
> > > 已合并代码，等待下一个新版本发布。
> > 
> > 
> > 我刚刚看了一下改动的代码，除了ul列表，ol列表也需要做同样的处理
> 
> 有序列表是没有过滤的，你可以试试
我刚刚试了，有序列表是可以的

**Comment by guMcrey** [comment]
@wangfupeng1988 你好呀, 目前这个问题仍然存在, 在对 ul 或 ol 设置了居中/居右后, 列表标记未跟随内容一起居中/居右, 如图(为官网的 demo 截图)
https://www.wangeditor.com/demo/get-html.html

<img width="240px" src="https://github.com/wangeditor-team/wangEditor/assets/26329117/cd08e45b-98df-4f1d-8861-36a916a81c52" />


&nbsp;

**解决方案:**
> 修改 packages/editor/demo/css/view.css
```css
.editor-content-view ul,
.editor-content-view ol {
  list-style-position: inside;  // 使得列表标记出现在列表项项目文本的内部
  padding-left: 20px;
}

```
