### ISSUE TITLE
使用暗黑主题时 代码高亮颜色很奇怪。

### ISSUE THREAD

**Issue by q812143836** [wangeditor-team/wangEditor#5645]
## 使用暗黑主题时 代码高亮颜色很奇怪。

*目前有没有为暗黑主题适配代码高亮颜色呢？*

## wangEditor V5

*请输入内容……*

## 是否查阅了文档 ？
是
![CodeColor](https://github.com/wangeditor-team/wangEditor/assets/54973061/2756820b-316b-4668-b1d2-a5228d004a1a)

请教一下目前是否有办法解决。望大哥大嫂们回复！

**Comment by goku1989** [comment]
text-shadow: 0 1px #fff;   调整#fff的颜色试试

**Comment by weilun0510** [comment]
怎么修改主题的

**Comment by lanut** [comment]
> 怎么修改主题的

@weilun0510 

我用的这个：

```less {5-8}
.dark {
    :deep(code) {
      text-shadow: none;
    }
}
```
